"""initial schema

Revision ID: c5fc4df90d0b
Revises: 
Create Date: 2026-08-12 21:11:25.719197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fc4df90d0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primename', sa.String(length=225), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('address', sa.String(length=225), nullable=False),
    sa.Column('pincode', sa.String(length=15), nullable=False),
    sa.Column('maxspots', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.Column('pincode', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=225), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('parking_spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('spot_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('A', 'O')", name='check_status_valid'),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_spot_lot_id'), ['lot_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserved_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=15), nullable=False),
    sa.Column('parking_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('leaving_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_at_booking', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['parking_spot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reserved_spots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reserved_spots_spot_id'), ['spot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reserved_spots_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserved_spots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reserved_spots_user_id'))
        batch_op.drop_index(batch_op.f('ix_reserved_spots_spot_id'))

    op.drop_table('reserved_spots')
    op.drop_table('user_roles')
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_spot_lot_id'))

    op.drop_table('parking_spot')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('parking_lots')
    # ### end Alembic commands ###
